package com.ultrawork.notes

import com.ultrawork.notes.data.repository.fake.FakeNotesRepository
import com.ultrawork.notes.model.Note
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test

class FakeRepositoriesTest {

    @Test
    fun `getNotes returns all seed notes`() = runTest {
        val repo = FakeNotesRepository()
        val notes = repo.getNotes()
        assertEquals(5, notes.size)
    }

    @Test
    fun `getNotes with favoritesOnly returns only favorited notes`() = runTest {
        val repo = FakeNotesRepository()
        val notes = repo.getNotes(favoritesOnly = true)
        assertTrue(notes.isEmpty())
    }

    @Test
    fun `toggleFavorite inverts isFavorited`() = runTest {
        val repo = FakeNotesRepository()
        val notes = repo.getNotes()
        val noteId = notes.first().id

        assertFalse(notes.first().isFavorited)

        val toggled = repo.toggleFavorite(noteId)
        assertTrue(toggled.isFavorited)

        val toggledBack = repo.toggleFavorite(noteId)
        assertFalse(toggledBack.isFavorited)
    }

    @Test(expected = NoSuchElementException::class)
    fun `toggleFavorite failure for unknown id`() = runTest {
        val repo = FakeNotesRepository()
        repo.toggleFavorite("non-existent-id")
    }

    @Test
    fun `notes have String id generated by UUID`() = runTest {
        val repo = FakeNotesRepository()
        val notes = repo.getNotes()
        notes.forEach { note ->
            assertTrue(note.id.isNotBlank())
            assertTrue(
                note.id.matches(
                    Regex("[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}")
                )
            )
        }
    }

    @Test
    fun `custom initial notes are used when provided`() = runTest {
        val custom = listOf(
            Note(id = "abc", title = "Custom", content = "Test")
        )
        val repo = FakeNotesRepository(initialNotes = custom)
        val notes = repo.getNotes()
        assertEquals(1, notes.size)
        assertEquals("abc", notes.first().id)
    }

    @Test
    fun `toggleFavorite persists in getNotes`() = runTest {
        val repo = FakeNotesRepository()
        val noteId = repo.getNotes().first().id

        repo.toggleFavorite(noteId)

        val favorites = repo.getNotes(favoritesOnly = true)
        assertEquals(1, favorites.size)
        assertEquals(noteId, favorites.first().id)
    }
}
